# Generated by Django 4.2.2 on 2023-07-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_alter_employee_empname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.IntegerField()),
                ('SurName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpName',
            field=models.CharField(max_length=20),
        ),
    ]
