# Generated by Django 4.2.2 on 2023-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_employeetable2_alter_employee_empname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeTable2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmpAddress',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmpName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmpSalary',
        ),
        migrations.AddField(
            model_name='employee',
            name='Address',
            field=models.CharField(default='kk', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='Date',
            field=models.DateTimeField(default='30'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Image',
            field=models.ImageField(default='none', upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='Name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(default='300'),
        ),
    ]
