# Generated by Django 4.2.2 on 2023-07-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_delete_employeetable2_remove_employee_empaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Date',
        ),
    ]
