# Generated by Django 4.2.2 on 2023-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_bikedetail_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedetail',
            name='custom_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
